name: Build packager Docker image
# This workflow is triggered on pushes to the repository.
on: 
  push:

jobs:
  Match-ref-patterns:
    runs-on: ubuntu-latest
    outputs:
      pattern-matched: ${{ steps.matching.outputs.pattern-matched }}
      registry: ${{ steps.matching.outputs.registry }}
      ref: ${{ steps.matching.outputs.ref }}
    steps:
      - uses: actions/checkout@v2
      - id: matching
        uses: drorvt/composite-match-ref-patterns@main

